version : '3'
 
services:
  inventory-api-pipeline:
    image: inventory-api-pipeline
    ports:
      - 9002:8080
    depends_on:
      - inventory-api-db-pipeline
  
  inventory-api-db-pipeline:
    image: inventory-api-db-pipeline
    ports:
      - 5432
